name: Docker Build Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  username: ${{secrets.DOCKERHUB_USERNAME}}
  password: ${{secrets.DOCKERHUB_PASSWORD}}
  PRODUCT_REPO_NAME: ${{secrets.PRODUCT_REPO_NAME}}
jobs:
  create-user-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Work Dir
        run: |
          echo $DOCKERHUB_USERNAME
          echo $DOCKERHUB_PASSWORD    
          echo $PRODUCT_REPO_NAME
      - name: Docker login
      - uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build user service docker image
        run: docker build . --file Dockerfile -t "$DOCKER_USERNAME/PRODUCT_REPO_NAME:latest"
      - name: Push user service docker image
        run: docker push "$DOCKER_USERNAME/PRODUCT_REPO_NAME:latest"
